id: P007123
initial_creation_type: ocr
source_metadata:
  id: bdr:W22705
  title: བཀའ་གདམས་གླེགས་བམ།
  author: ''
  volumes:
    430e4dc8836e4159b1de343735114a9a:
      image_group_id: I00KG03587
      title: ''
      volume_number: 1
      total_pages: 313
ebook_metadata:
  title: བཀའ་གདམས་གླེགས་བམ།
  author: ''
  sku: P007123
  cover: cover.jpg
  layers:
  - pagination
