id: P007123
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 12:43:12.908843
source_metadata:
  id: bdr:W22705
  title: བཀའ་གདམས་གླེགས་བམ།
  author: ''
  volumes:
    e57e739172f848eeae12d0a1e34df7de:
      image_group_id: I00KG03587
      title: Volume 1 of bka' gdams glegs bam
      volume_number: 1
      total_pages: 313
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
