id: I0A10ED0F
legacy_id: P007123
ocr_import_info:
  bdrc_scan_id: W22705
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T20:59:34'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T00:50:54.124074+00:00'
last_modified: 2022-09-02 08:51:04.455168
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22705
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW22705
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བཀའ་གདམས་གླེགས་བམ།
  author: རྒྱལ་བའི་འབྱུང་གནས།
statistics:
  ocr_word_mean_confidence_index: 0.6172049048805213
  ocr_word_median_confidence_index: 0.6600000262260437
quality: null
bases:
  I00KG03587:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03587
      total_pages: 313
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG03587.txt
    statistics:
      ocr_word_median_confidence_index: 0.6600000262260437
      ocr_word_mean_confidence_index: 0.6172049048805213
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
