id: I0A10ED0F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T21:01:38+00:00'
last_modified: '2022-06-09T06:13:28.871960+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22705
  title: བཀའ་གདམས་གླེགས་བམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0099:
      image_group_id: I00KG03587
      title: Volume 1 of bka' gdams glegs bam
      total_pages: 313
      order: 1
      base_file: 0099.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
